### ISSUE TITLE
Double tapping a selected comment pushes comments below offscreen

### ISSUE THREAD

**Issue by The0x539** [ccrama/Slide#1074]
Slide version: 4.6.1.25-a6cb3ac
Android version: 6.0.1 or whatever

**Comment by ccrama** [comment]
Fixed!

**Comment by The0x539** [comment]
Still happening for me, just a bit differently.

**Comment by Alexendoo** [comment]
It occurs whenever you go to expand the comment again whilst the retraction animation is playing

**Comment by The0x539** [comment]
Good catch

**Comment by kufii** [comment]
is this included in the latest release? the issue is still occurring for me, except now it happens after 4 taps

**Comment by The0x539** [comment]
Yep.
