### ISSUE TITLE
only around 30 posts are loaded 

### ISSUE THREAD

**Issue by perler** [ccrama/Slide#1095]
Slide version:4.6.1 (happens since 4.6)
Android version: 6.0
on the front page I can scroll until the first reload, which never ends. when I swipe to another subreddit the same. some subreddits are empty and the loading thingy just spins.. also, comments are not loaded at all (when entering a topic) 

I already cleared everything (cache and settings, then restored a backup) to no avail.

**Comment by ccrama** [comment]
Sounds like you are in offline mode. What does the title of the drawer say?

**Comment by perler** [comment]
I'm not quite sure where to look and I did not consciously enable it.
![screenshot_20160228-183301](https://cloud.githubusercontent.com/assets/623092/13380897/fb3e9748-de4d-11e5-87c1-72f66b6d13b8.png)

**Comment by ccrama** [comment]
Where is your account name? That looks quite strange

**Comment by perler** [comment]
I removed it for privacy purposes :)

but there was just the account name, nothing more.

On Sun, Feb 28, 2016 at 8:42 PM ccrama <notifications@github.com> wrote:

> Where is your account name? That looks quite strange
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrama/Slide/issues/1095#issuecomment-189932120>.
>
--

**Comment by ccrama** [comment]
Ah, alright. And try switching the sorting mode, I think that is your issue

**Comment by perler** [comment]
yes, there seems to be an issue. I cannot change the sorting mode. I choose
the radio button, the subreddit is reloaded, but when I tap the sorting
mode symbol again, it's still at "hot"

On Sun, Feb 28, 2016 at 8:53 PM ccrama <notifications@github.com> wrote:

> Ah, alright. And try switching the sorting mode, I think that is your issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrama/Slide/issues/1095#issuecomment-189933756>.
>
--

**Comment by ccrama** [comment]
Should be fixed now, the sorting switcher now works

**Comment by perler** [comment]
unfortunately, in 4.7 it is not fixed.

**Comment by perler** [comment]
ok, let me update this, I just let the tablet lay around for 5 minutes and the articles actually load after a very, very long time, minutes, not seconds.

internet speed is good, reddit is up and I tried sync pro and posts are loaded normally.

**Comment by perler** [comment]
I did some more tests:

I removed the sd card (I suspected a corruption) - no changes
I removed all data - problem resolved 
I recreated my settings (font size, layout) by hand (not from the backup) - problem still solved 
I log into my reddit account - problems reappear. 

meanwhile everything was working fine in other reddit clients (here: sync pro) 

does this help? (could @ccrama please re open the issue?) I am a supporter, so a little feedback would be nice :-)

**Comment by Alexendoo** [comment]
The issue is only apparent when you're logged in? Very strange. What device is this on may I ask?

**Comment by perler** [comment]
actually on two devices; nvidia shield k1 and nexus 5x

some more observations:

some imgur links don't open in overlay which open fine in the external browser 
I _think_ I tried the synccit integration once and this could coincide with the problem (but removed it a long time ago.

**Comment by Alexendoo** [comment]
If you have a second account you can log into, would you be able to clear data + test that?

**Comment by perler** [comment]
Good idea, I will create one and give it a try tomorrow.

**Comment by perler** [comment]
ok, I treid with a secondary account and the problem went away. I switch
back to my primary account, the problem is there again.

is there a contact at reddit who is willing to investigate this problem?

On Sun, Mar 13, 2016 at 9:10 PM Alex Macleod <notifications@github.com>
wrote:

> If you have a second account you can log into, would you be able to clear
> data + test that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrama/Slide/issues/1095#issuecomment-196044588>.
>
--

**Comment by ccrama** [comment]
Should be fixed now

**Comment by perler** [comment]
should it be fixed in the play store version or the github version?

On Tue, Mar 22, 2016 at 4:11 PM ccrama <notifications@github.com> wrote:

> Closed #1095 <https://github.com/ccrama/Slide/issues/1095>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrama/Slide/issues/1095#event-598837221>
>
--

**Comment by ccrama** [comment]
Github

**Comment by perler** [comment]
Brillo! It looks as this fix worked! Thanks. (There is a similar bug but
which isn't as showstopping, I will open a separate issue on github)

On Wed, 23 Mar 2016, 03:04 ccrama, <notifications@github.com> wrote:

> Github
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ccrama/Slide/issues/1095#issuecomment-200129148>
>
--
