### ISSUE TITLE
Cannot Successfully Authenticate with Synccit

### ISSUE THREAD

**Issue by dimalantak** [ccrama/Slide#1565]
Slide version: 5.3.1
Android version: 6.0.1

Login information for Synccit is correct but Slide for Reddit will never successful authenticate.

**Comment by ccrama** [comment]
Does it give an error message, and are you sure Slide is the only app that is currently using that key? Keys can only be used on one device at a time

**Comment by dimalantak** [comment]
Error message is "Could not authenticate Make sure your username and authentication key are correct!"

Yes, Slide is the only app using this particular key.

As soon as synccit.com is back online I will try creating another key. Although I am pretty sure I did this already when I was doing some troubleshooting.

Thanks for the quick response.

**Comment by ccrama** [comment]
Oh, if synccit.com is offline then the server is offline :P

**Comment by dimalantak** [comment]
That is only the case for right now (hopefully).

When I was trying to set synccit up with Slide yesterday, the website was working.

I was finally able to reach the site and create a new auth key. However, even with that new auth key I do get the same error.

**Comment by Nxt3** [comment]
This is a bug. It's weird--but press "Save" twice; you'll get the error the first time--and then the second time, it will work.

**Comment by dimalantak** [comment]
Interesting. I "wish" I had that bug as even with that tip, I am still unable to log in.

**Comment by ccrama** [comment]
I am able to log in successfully @dimalantak, try making new keys and check for case. 

@Nxt3  that bug is because the read execute was put into the handler which was designed to wait for that to finish, so it just waits, executes but then says it's not good because it didn't execute. Has been fixed.

**Comment by dimalantak** [comment]
I did create another key and also checked case with no success. 
![13063862_1352725004753371_667005493_o](https://cloud.githubusercontent.com/assets/18562864/14797409/8e404940-0ae7-11e6-8d06-beef66a70093.jpg)

I even created a new synccit account to see if my problem was with my synccit account. 
I also uninstalled and reinstalled Slide now version 5.3.2.4. Both resulted in the same error message.

**Comment by ccrama** [comment]
If it has the button that says "Disconnect" from synccit, that means you have already authenticated and might be why it's failing. Click disconnect and type it back in, does it work after clicking twice?

**Comment by dimalantak** [comment]
It works! I don't know if clicking twice did the trick. But either way I still get the error. 

With that issue semi out of the way, Slide can now become my primary Reddit app. Thank you.

**Comment by ccrama** [comment]
The double auth thing has been fixed for the next update. Glad to hear it's working!
