### ISSUE TITLE
Top of posts are cut off

### ISSUE THREAD

**Issue by robrobinbin** [ccrama/Slide#1812]
The top of all posts are cut off when viewing them. I think it also happens with post that have a preview image, but that isn't that irritating.

**Examples:**

I'm viewing this post:

**I was disappointing to have to pay for my new roof**
> they promised me it would be on the roof

[Screenshot](https://i.imgur.com/sE11fKt.png): I scrolled all the way up, yet I'm missing part of the title

[This](https://i.imgur.com/fAGk9n7.png) is a post with a preview image. I guess part of the images is cut off, but you couldn't really tell.

To be clear: there is nothing wrong or cut-off with [normal list views](https://i.imgur.com/UTD9BX1.png)

Slide version: 5.3.8
Android version: 5.1

**Comment by ccrama** [comment]
Do you have any way to reproduce this? I cannot get this to happen on any of my devices

**Comment by robrobinbin** [comment]
I removed the application and reinstalled it from the play store (I also tried f-droid). The playstore mentions the change log for 5.3.9, but the app version is 5.3.1.9 (which is smaller IMO). The bug is still present on a clean install of the app, without any settings changed. I think the bug wasn't present a couple of releases ago. I'm using a Fairphone 2, with the latest Fairphone OS, which is based on Android 5.1. Maybe the fault is theirs, their OS isn't without bugs. I can't find any other apps with the same bug though... Anyhow, this makes Slide pretty hard to use.

**Comment by septemus** [comment]
@robrobinbin Versioning mistake. Should be 5.3.9.1. The way I usually fix it is by swiping the app out of recents and then re-opening it. YMMV.

**Comment by amici-ursi** [comment]
Same problem here for a couple versions. Screenshots of the issue, phone, and app version attached.

![4whbbt8](https://cloud.githubusercontent.com/assets/6052722/15629489/84fb073c-24df-11e6-9e15-ff47a74fa18e.png)
![fgrczoj](https://cloud.githubusercontent.com/assets/6052722/15629491/84fc412e-24df-11e6-9d10-bfcc42dc1155.png)
![gk9g6sn](https://cloud.githubusercontent.com/assets/6052722/15629490/84fbb02e-24df-11e6-9a42-5112119f36c2.png)
![ityvbfr](https://cloud.githubusercontent.com/assets/6052722/15629492/84fd587a-24df-11e6-89fa-ccf9dfeb0762.png)
![ubsxuzu](https://cloud.githubusercontent.com/assets/6052722/15629493/84fe7b7e-24df-11e6-9033-bd1e33a4a7f0.png)
![ujdvz6b](https://cloud.githubusercontent.com/assets/6052722/15629494/85001e3e-24df-11e6-98fb-efb6d2eab79f.png)

**Comment by ccrama** [comment]
Am I correct in assuming you are all on KitKat?

**Comment by septemus** [comment]
I am not; I was just proposing a temporary solution because this happened a while ago before you fixed it (on MM, at least).

**Comment by ccrama** [comment]
I haven't ever seen this behavior before, the only reason it would occur is if your device is returning 0 for the vertical pixel height (while calculating the dp height), which might mean it's device-specific

**Comment by septemus** [comment]
Interesting. However, I have not run into this bug for quite a while.

**Comment by ccrama** [comment]
Did you change roms or change anything else specific to your device?

**Comment by ccrama** [comment]
I think I fixed it (although I still could not reproduce). Let me know if it is in the next update

**Comment by Alexendoo** [comment]
https://www.reddit.com/r/slideforreddit/comments/4u0kd1/found_another_one_of_those_cutoff_titles/ reports that it's still here in 5.4

**Comment by Nxt3** [comment]
@Alexendoo This is a different issue. This issue is talking about the toolbar covering up the title when in comments.

**Comment by robrobinbin** [comment]
Sorry for my slow reaction time. The bug is still present on every comment thread I view with Slide. I have re-installed Slide multiple times and I'm using the latest version from the play store.

**Comment by ccrama** [comment]
There were some underlying changes to the API in v24, along with an update to all the support libraries. Has anyone seen this in v5.4.3?

**Comment by ccrama** [comment]
Assuming this is now fixed. If not, please let me know and we can re-open it. Tested on KitKat without issues on my testing device

**Comment by Nxt3** [comment]
I ran into it on Nougat just now. :(

**Comment by ccrama** [comment]
@Nxt3 you couldn't scroll up in comments? The code for the spacer height is mostly yours :P

**Comment by Nxt3** [comment]
Oops wrong issue.

**Comment by robrobinbin** [comment]
The bug is still present. I installed Android Studio and cloned the project, but I've got little Android experience (I know java though). I can see the bug when I run from Android Studio on my device. Can you give me a pointer to which files I should look to find a workaround / fix ?
